# Generated by Django 5.1.7 on 2025-03-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publication_year',
            field=models.IntegerField(null=True),
        ),
    ]
